Adds an optional timeout that a port will remain bound after returning
google/python_portpicker pull request #31
Opened 2022-06-15 04:50 UTC by gpshead

This is for CLI users in the non-recommended non-portserver case. The logic here comes from our internal `googletest.sh` bash testing framework to replace some existing `perl -e` and `python -c` invocations that it makes doing an equivalent. Instead we'd just have it always invoke portpicker with this in place.

Enhances the testing so that portserver usage is covered in CI by launching our own portserver when feasible. Primarily only on Linux as written.

bumps the version number.

2022-07-06 19:46 UTC, gpshead commented
Internal testing has this holding up well as a replacement for our existing ~80 use cases of the logic this PR was derived from.

2022-07-06 22:12 UTC, gpshead commented
tagging @jerub for a code review.

2022-07-07 08:22 UTC, jerub requested changes
Overall LGTM. I reviewed the code of `_spawn_bound_port_holding_daemon` and double checked some socket semantics on linux to make sure it wouldn't have undesired behavior.

2022-07-07 08:22 UTC, jerub commented on src/portpicker.py
> +    socket_families = (socket.AF_INET6, socket.AF_INET)
Prefer a single-assignment style:

```
# Bind the return socket last
if return_socket is None or return_family == INET:
  socket_families = (INET6, INET)
elif return_family == INET6:
  socket_families = (INET, INET6)
else:
  raise ValueError(...)
```

2022-07-07 19:17 UTC, gpshead commented on src/portpicker.py
> +    socket_families = (socket.AF_INET6, socket.AF_INET)
much nicer, thanks!

2022-07-07 19:17 UTC, gpshead commented on ChangeLog.md
> +    ports chosen *without a portserver* to be kept bound to a socket by a child
thanks!

2022-07-07 19:24 UTC, merged